### ISSUE TITLE
Ability to label pre-selected variables available for item grouping

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#16] opened 2017-09-28 19:37 UTC
Input from Karen B

Spencer: "label groups can be handled via webCharts.multiply() on cohort or treatment group or however they want to group the timelines"

**Comment by emmorris** [comment] 2017-10-03 20:04
Maybe a duplicate of #6?  Britt will confirm with Karen and Brian.

**Comment by brittsikora** [comment] 2017-10-05 20:59
This is a confirmed to be a duplicate of #6

**Closed** 2017-10-16 15:20 UTC
Labels: duplicate
