### ISSUE TITLE
Move population/participant text out of controls container.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#48] opened 2017-11-07 02:01 UTC
Beneath controls above legend, centered.

**Comment by jwildfire** [comment] 2017-11-14 21:33
Now in sidebar. Looks good.

**Comment by dschwentker** [comment] 2017-12-15 20:41
Tested and confirmed. This looks like a duplicate of #63 to me.

**Closed by dschwentker** 2017-12-15 20:41 UTC
